// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  newline = 21,
  newlineEmpty = 22,
  eof = 23,
  incomingNewline = 24,
  incomingEOF = 25,
  stafflineSep = 26,
  Tablature = 1,
  Staves = 2,
  StaffLineGroup = 3,
  StaffLine = 4,
  MeasureLineName = 5,
  MeasureLine = 6,
  Hammer = 7,
  Pull = 11,
  Slide = 12,
  Multiplier = 13
