// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {externSpaces, newlines, lookaheads} from "./tokens"
export const parser = LRParser.deserialize({
  version: 13,
  states: "$zOVQPOOOOQW'#C`'#C`O[OXO'#C_OjQTO'#C^OuQTOOOOOW'#Cb'#CbO}OXO,58yOOOW'#Ca'#CaO}OXO,58yOOQS,58y,58yOVQPO'#CcO!]QTO,58xO!hQTO'#CdOuQTOOQOQPOOOOOW-E6`-E6`OOOW,58{,58{OOQS1G.e1G.eO!sOXO1G.eOOOW-E6_-E6_OOQS,58},58}OOQS-E6a-E6aOOQS'#Ce'#CeO!hQTO,59OOOQS,59O,59OOOQS-E6b-E6bOOQS7+$P7+$PPbOPO'#CbOOQS-E6c-E6cOOQS1G.j1G.j",
  stateData: "#R~ObOS~OcPO~O_XO`XObTOcPO~O[YO]QX^QX~O][O^^O~O_aO`aObTOcPO~O[YO]Qa^Qa~O[fO]fOcPO~O_jO`jObTOcPO~O",
  goto: "!pYPPZdl{!R!^!d!jQSOQh[RmgURO[gRdYWQOY[gSVQWV`UbkQWQRcWQUQU_UbkRbWQZRReZQ]SRi]Qg[Rlg",
  nodeNames: "⚠ Tablature Staves StaffLineGroup StaffLine",
  maxTerm: 19,
  skippedNodes: [0],
  repeatNodeCount: 5,
  tokenData: "!O~RRXY[pq[#[#]a~aOb~~dP#X#Yg~jP#`#am~pP#`#as~vP#c#dy~!OOc~",
  tokenizers: [0, externSpaces, newlines, lookaheads],
  topRules: {"Tablature":[0,1]},
  tokenPrec: 0
})
