// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  extSpaces = 11,
  newline = 12,
  newlineEmpty = 13,
  eof = 14,
  incomingNewline = 15,
  incomingEOF = 16,
  Tablature = 1,
  Staves = 2,
  StaffLineGroup = 3,
  StaffLine = 4
