// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {newlines, lookaheads, stafflineSeparator} from "./tokens"
import {NodeProp} from "@lezer/common"
export const parser = LRParser.deserialize({
  version: 13,
  states: "'bOVQXOOOeQPO'#C`OmQQO'#C`OOQW'#Cj'#CjO{QXO'#C_OOQS'#C_'#C_O!ZQTO'#C^O!fQTOOOmQQO,58zOOQO'#Cd'#CdO!nQPO'#CeO!sQPO'#CfOOQO'#C|'#C|O!xQQO'#C{OOQO'#C{'#C{OOQO'#Cl'#ClO#dQQO'#CbOOQ`'#Ck'#CkO#uQbO,58zOOQW-E6h-E6hOOQS,58y,58yOVQXO'#CmO$ZQTO,58xO$fQ]O'#CnO!fQTOOQOQPOOO$zQbO1G.fO%`QPO,59POOQO,59Q,59QOpQQO,58}OpQQO,59ROpQQO,59SOOQO-E6j-E6jOOQ`,58|,58|OOQ`-E6i-E6iOOQW1G.f1G.fOOQS,59X,59XOOQS-E6k-E6kOOQ['#Co'#CoO$fQ]O,59YOOQS,59Y,59YOOQS-E6l-E6lOOQW7+$Q7+$QOOQO1G.k1G.kOOQO1G.i1G.iOOQO1G.m1G.mOOQO1G.n1G.nOOQ[-E6m-E6mOOQS1G.t1G.t",
  stateData: "%e~OlOS~OTPOhTOiTOmQO~OmWOnWO~On_OqXOrYOtZO~OTPOhdOidOmQO~OeeOfQXgQX~OfgOgiO~OqkO~OqlO~OumOvnOwoOmoXnoXqoXroXtoX~OmqOn_OqXOrYOtZO~O]sOjsOn_OqXOrYOtZO~OeeOfQagQa~OTPOevOfvOhTOiTOmQO~O]zOjzOn_OqXOrYOtZO~Os{O~O",
  goto: "$bqPPr{!TP![!b!l!l!l!b!bP!v#P#Z#d#j#pPPPPPPPPPPP#v$WQVOQxgR!QwUUOgwRteZROSegwXaQWbja^QW`bjmnoa[QW`bjmnoWSOegwRcSQbQQjWTrbjW`QWbjRp`QfURufQhVRyhQwgR!PwY_QW`bjQ|mQ}nR!Ooa]QW`bjmno",
  nodeNames: "⚠ Tablature Staves StaffLineGroup StaffLine MeasureLineName MeasureLine Hammer Fret Harmonic Grace Pull Slide Multiplier",
  maxTerm: 39,
  nodeProps: [
    [NodeProp.group, -3,7,11,12,"MeasureComponentGroup",-3,8,9,10,"MeasureComponent"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 6,
  tokenData: "$y~RkXY!vpq!v}!O!{!P!Q#Q!Q![#V![!]#d!c!d#t!d!e#t!f!g#t!g!h#t!i!j#y!j!k$Q!r!s$V!z!{$[!}#O$g#O#P#Q#P#Q$l#T#U#t#U#V#t#W#X#t#X#Y#t#Z#[#y#[#]$q#d#e$V#g#h#Q#l#m$[#p#q#d~!{Ol~~#QOn~~#VOw~~#[Pq~!Q![#_~#dOq~~#iQm~![!]#o#p#q#o~#tOm~P#yOTPR$QOTPtQQ$VOuQ~$[Ov~~$_P!Q![$b~$gO]~~$lOr~~$qOs~R$vPuQ#]#^#t",
  tokenizers: [0, 1, newlines, lookaheads, stafflineSeparator],
  topRules: {"Tablature":[0,1]},
  tokenPrec: 0
})
